repos:
  # python import sorting - will amend files
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort

  # python code formatting - will amend files
  - repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
      - id: black

  # update syntax where appropriate
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade

  # formatting of django templates
  - repo: https://github.com/rtts/djhtml
    rev: v1.4.9
    hooks:
      - id: djhtml

  # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bandit
          - flake8-print

  # python static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args:
        - --disallow-untyped-defs
        - --disallow-incomplete-defs
        - --check-untyped-defs
        - --no-implicit-optional
        - --ignore-missing-imports
        - --follow-imports=silent
